config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    # resources :groups do
    #   resources :payments, only: %i[index show new create]

    # end  
  # get '/welcome', to: 'welcome#index'
  
  resources :users, only: [:index] do
    resources :groups, only: %i[index new create show] do
      resources :payments, only: %i[new create]
    end
  end
  # root 'groups#index'
  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :payment_items, dependent: :delete_all
  has_many :payments, through: :payment_items, dependent: :delete_all
  has_one_attached :icon

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount_by_group(group_id)
    payments.joins(:payment_items).where(payment_items: { group_id: group_id }).sum('payments.amount')
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :payment_items
  has_many :groups, through: :payment_items

  validates :amount, presence: true
  validates :name, presence: true
end

app/models/payment_item.rb
class PaymentItem < ApplicationRecord
  belongs_to :group
  belongs_to :payment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :payments, foreign_key: :author_id, dependent: :destroy
  has_many :groups

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @groups = current_user.groups.all.includes(:payments)
  end

  def show
    @user = current_user
    @group = Group.find(params[:id])
    @payments = @group.payments.order('created_at DESC')
  end

  def new
    @user = current_user
    @group = Group.new
  end

  def create
    @user = current_user
    group = Group.new(
      name: new_group_params['name'],
      icon: new_group_params['icon'],
      user_id: current_user.id
    )
    if group.save
      flash[:success] = 'Category was created successfully'
      redirect_to user_groups_path(user_id: current_user.id)
    else
      flash[:alert] = 'Category was not created'
    end
  end

  private

  def new_group_params
    params.require(:new_group).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @payments = @group.payments.order(created_at: :desc)
  end

  def new
    @payment = current_user.payments.new
    @group = Group.find(params[:group_id])
    @groups = current_user.groups
  end

  def create
    @payment = Payment.new(name: payment_params[:name], amount: payment_params[:amount], author_id: current_user.id)
    @group = Group.find(params[:group_id])

    if @payment.save
      @payment_item = PaymentItem.new(payment_id: @payment.id, group_id: params[:payment_item][:group_id])

      if @payment_item.save
        redirect_to user_group_path(current_user, @group), notice: 'Payment was successfully created.'
      end

    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def payment_params
    params.require(:payment_item).permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    return unless user_signed_in?

    redirect_to user_groups_path(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<%= render partial: '/groups/shared/nav_page', locals: { title: 'Budget Categories', backurl: user_groups_path(user_id: current_user.id) } %>

<div class="container">
  <% @groups.each do |group| %>
    <%= link_to user_group_path(user_id: @user.id, id: group.id), class: 'custom-category-links' do %>
      
      <div class="image"><%= image_tag group.icon, style: 'width: 200px;' %></div>
      <div class="name">
        <h3><%= group.name %></h3>
      </div>
      <div class="total">$<%= '%.2f' % group.total_amount_by_group(group.id) %></div>
    <% end %>
  <% end %>

  <button class="new-category-button">
    <div><%= link_to 'Add new category', new_user_group_path(user_id: current_user.id) %></div>
  </button>
</div>

app/views/groups/new.html.erb
<%# <h2>New Category</h2> %>

<%= render partial: 'groups/shared/form', locals: { group:@group }%>



<%# <%= link_to 'Back', user_groups_path(user_id: current_user.id) %> 

app/views/groups/shared/_form.html.erb
<%= form_with url: user_groups_path(user_id: current_user.id), model: group, method: :post, scope: :new_group do |form| %>

<header>
    <div class="title">
      <div>
        <%= link_to (:back) do %>
          <%= image_tag 'back.svg' %>
        <% end %>
      </div>
      <div><h2>New Category</h2></div>
      <div><%= form.submit "Create" %></div>
    </div>
  </header>

<div class="form-body">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
      <%= form.label :icons %>
	    <%= form.file_field :icon %>
    </div>
  </div>
<% end %>

app/views/groups/shared/_nav_page.html.erb
<header>
  <div class="title">
    <div></div>
    <div><h2>Categories</h2></div>
    <div></div>
  </div>

  <nav>
  <ul>
    <li>
      <%= link_to 'logout', destroy_user_session_path, data: {turbo_method: :delete}  %>
    </li>
  </ul>
</nav>
</header>

app/views/groups/show.html.erb
<header>
    <div class="title">
      <div>
        <%= link_to user_groups_path do %>
          <%= image_tag 'back.svg' %>
        <% end %>
      </div>
      <div><h2><%=@group.name%></h2></div>
       <div><%= link_to "Add a new transaction", new_user_group_payment_path(current_user,@group), class: "button_text" %>
  </div>
    </div>
  </header>

<div class="group_holder">
  <div class="group_card">
    <div class="card_element">
      <div class="picture_holder">
        <%= image_tag @group.icon, style: 'width: 200px;' %>
      </div>
      <div class="name_holder">
        <h5 class="group_name">
          <%=@group.name%>
        </h5>
        <p class="detail_description">This is a short explanation for the group expenses</p>
      </div>
    </div>
    <hr>
    <div>
      <% @payments.each do |payment| %>
      <div class="transaction">
        <p>Transaction No <%=payment.id%></p>
        <div class="transaction_detail">
          <p><%=payment.created_at.strftime('%d %B %Y')%></p>
          <p>$<%=payment.amount%></p>
        </div>
      </div>
      <% end %>
    </div>
    <hr>
    <div class="total_transaction">
      <h5 class="total_font">TOTAL PAYMENT</h5>
      <h5 class="total_font">$<%=number_with_delimiter(@group.total_amount_by_group(@group.id))%></h5>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/pages/hello.html.erb
<h1>Pages#hello</h1>
<p>Find me in app/views/pages/hello.html.erb</p>

app/views/payments/new.html.erb
 <%# <%= render partial:'/groups/shared/nav_page', locals: {title: 'Add a spending', backurl: user_group_path(author_id:@user.id,id:@group.id)}  %> 

<%= render partial: 'payments/shared/form', payment:@payment%>

app/views/payments/shared/_form.html.erb
<%= form_with model: [current_user, @group, Payment.new], url: user_group_payments_path(current_user, @group) do |form| %>

<header>
  <div class="title">
    <div><%= link_to(:back) do %>
      <%= content_tag(:div) do %>
      <i class="material-icons">BACK</i>
      <% end %>
      <% end %></div>
    <div>
      <h2>New Payment</h2>
    </div>
    <div><%= form.submit "Submit" %></div>
  </div>
</header>

<div class="form-body">
  <%= form_with url: user_group_payments_path(current_user, group_id:@group.id), method: :post,
  scope: :payment_item , local: true, class: "category-form" do |f| %>
  <div class="custom-form-field">
    <%= f.text_field :name, required:true,
    placeholder:'Name',class:'custom-form-field-text' %>
  </div>

  <div class="custom-form-field">
    <%= f.number_field :amount, step:0.10,min:0 , required:true,
    placeholder:'Amount', class:'custom-form-field-text' %>
  </div>

  <div class="custom-form-field-selection">
    <%= f.collection_select :group_id, @current_user.groups, :id, :name, { prompt: 'Select a group' }, required: true %>
  </div>
  <% end %>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<p class="notice"><%= notice %></p> 
<p class="alert"><%= alert %></p> 

app/views/users/index.html.erb
<section class="splash">
  <h1>
    Budget tracker App
  </h1>
  <div>
    <%= link_to 'Login', new_user_session_path, class:'login' %>
    <%= link_to 'Sign up', new_user_registration_path, class:'signup' %>
  </div>
</section>